language: node_js

node_js:
  - "stable"

before_install:
  # update first
  - sudo apt-get update -qq
  # install sans and serif Chinese fonts
  - sudo apt-get install -y ttf-wqy-microhei fonts-arphic-gbsn00lp
  # Install Gitbook
  - npm install gitbook-cli -g
  # Clone the repository
  - git clone --depth=10 --branch=master git://github.com/billryan/algorithm-exercise.git

before_script:
  # install calibre latest version
  - sudo -v && wget --no-check-certificate -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
  # install qiniu sync
  - wget http://devtools.qiniu.io/qiniu-devtools-linux_amd64-current.tar.gz
  - tar xfz qiniu-devtools-linux_amd64-current.tar.gz
  - cp algorithm-exercise/conf/qiniu_sync.json ./

script:
  # replace with real key
  - sed -i "s/AccessKey/$QAK/g" qiniu_sync.json
  - sed -i "s/SecretKey/$QSK/g" qiniu_sync.json
  - mkdir -p ./upload
  - mkdir -p ./algorithm_html
  - cd algorithm-exercise
  - gitbook build ./ --format=json
  - gitbook pdf ./ ../upload/algorithm.pdf
  - gitbook epub ./ ../upload/algorithm.epub
  - gitbook mobi ./ ../upload/algorithm.mobi
  - gitbook build ./ --output=../algorithm_html

after_success:
  # copy website html files to upload
  - cd ../
  - tar cvzf algorithm_html.tar.gz algorithm_html/
  - cp algorithm_html.tar.gz upload/
  # upload to qiniu
  - ./qrsync ./qiniu_sync.json
  # test for source hans pro fonts
  - mkdir -p /tmp/noto
  - cd /tmp/noto
  - wget http://www.google.com/get/noto/pkgs/Noto-hinted.zip
  - unzip Noto-hinted.zip
  - mkdir -p ~/.fonts/noto
  - mv *.otf ~/.fonts/noto
  - cd /tmp
  - wget -O fonts.conf https://gist.githubusercontent.com/ingramchen/21533bbfc0d2dead94a7/raw/c750592f750cb446f6a6a19d75892c7d2fb5395f/gistfile1.xml
  - cp -i fonts.conf ~/.fonts.conf
  - sudo fc-cache -f -v

branches:
  only:
    - master
