language: node_js

node_js:
  - "stable"

before_install:
  # add id_rsa private key
  - openssl aes-256-cbc -K $encrypted_c2697660bfd7_key -iv $encrypted_c2697660bfd7_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - cp ssh_config ~/.ssh/config
  - git config --global user.name "billryan"
  - git config --global user.email yuanbin2014@gmail.com
  # update first
  - sudo apt-get update -qq
  # install sshpass
  - sudo apt-get install -y sshpass
  # install Chinese fonts
  - sudo apt-get install -y fonts-arphic-gbsn00lp fonts-arphic-bsmi00lp
  # Install Gitbook
  - npm install gitbook-cli -g
  - npm install svgexport -g
  - cd ~
  - cp ./scripts/rename_ebook.sh .
  - chmod +x rename_ebook.sh
  - git clone git@github.com:billryan/algorithm-exercise.git

before_script:
  # install calibre latest version
  - sudo -v && wget --no-check-certificate -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"

script:
  - mkdir -p ~/upload
  # build static website
  - cd ~/algorithm-exercise/
  - gitbook install && gitbook build .
  - gitbook pdf .
  - gitbook epub .
  - gitbook mobi .
  - mv *.pdf *.epub *.mobi ~/upload
  - cd ~/upload
  - sh ~/rename_ebook.sh

after_success:
  - cd ~/algorithm-exercise
  - git checkout deploy
  - cp ~/upload/*.epub epub
  - cp ~/upload/*.pdf pdf
  - cp ~/upload/*.mobi mobi
  - git add epub
  - git add pdf
  - git add mobi
  - git commit -m "Updated $(date)"
  - git push -u gitcafe HEAD:deploy --force
  - git push -u origin HEAD:deploy --force
#  # cd ~
#  - cd ~
#  # install source code pro
#  - mkdir -p /tmp/code_pro
#  - cd /tmp/code_pro/
#  - wget https://github.com/adobe-fonts/source-code-pro/archive/1.017R.tar.gz
#  - tar xzf 1.017R.tar.gz
#  - mkdir -p ~/.fonts/fontconfig/conf.d/
#  - cp source-code-pro-1.017R/OTF/*.otf ~/.fonts/
#  - sudo fc-cache -f -v
#  # install google noto Simplified Chinese
#  - mkdir -p /tmp/noto
#  - cd /tmp/noto
#  - wget https://www.google.com/get/noto/pkgs/NotoSansCJKSC-hinted.zip 
#  - https://www.google.com/get/noto/pkgs/NotoSerif-unhinted.zip
#  - unzip NotoSansCJKSC-hinted.zip
#  - unzip NotoSerif-unhinted.zip
#  - mkdir -p ~/.fonts/noto
#  - mv *.otf ~/.fonts/noto
#  # update fonts
#  - cd ~
#  - cp ~/algorithm-exercise/conf/10-latin.conf ~/.fonts/fontconfig/conf.d/
#  - cp ~/algorithm-exercise/conf/15-noto-cjksc.conf ~/.fonts/fontconfig/conf.d/
#  - cp ~/algorithm-exercise/conf/20-noto-cjk.conf ~/.fonts/fontconfig/conf.d/
#  - sudo fc-cache -f -v
#  # generate different locales
#  - sudo locale-gen zh_CN.UTF-8
#  - cd ~/algorithm-exercise
#  - export LANG=zh_CN.UTF-8
#  - gitbook pdf ./ ~/upload/algorithm_billryan_desktop.pdf
#  - ~/qrsync ~/qiniu_sync.json

branches:
  only:
    - master
