language: node_js

node_js:
  - "stable"

before_install:
  # Install Gitbook
  - npm install gitbook-cli -g
  # Clone the repository
  - git clone https://github.com/hexojs/hexojs.github.io .deploy
  - git clone --depth=10 --branch=master git://github.com/billryan/algorithm-exercise.git

script:
  - cd algorithm-exercise
  - gitbook build ./ --format=json
  - gitbook build

branches:
  only:
    - master
